CREATE TABLE internships (
    id bigint generated by default as identity primary key,
    company text,
    role text,
    stipend text,
    location text,
    lat real,
    lng real,
    skills text,
    description text
);

CREATE TABLE applications (
    id bigint generated by default as identity primary key,
    internship_id bigint references internships(id),
    applicant_name text,
    status text default 'pending'
);

CREATE TABLE saved_internships (
    internship_id bigint references internships(id) primary key
);

create or replace function get_saved_internships() 
returns table (id bigint, company text, role text, stipend text, location text, lat real, lng real, skills text, description text, isSaved boolean) as $$
begin
  return query 
  select i.*, true as isSaved
  from internships i
  join saved_internships s on i.id = s.internship_id;
end; 
$$ language plpgsql;

create or replace function get_random_internships(limit_count int) 
returns table (id bigint, company text, role text, stipend text, location text, lat real, lng real, skills text, description text) as $$
begin
  return query 
  select * from internships order by random() limit limit_count;
end; 
$$ language plpgsql;